# Generated by Django 2.1.2 on 2018-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPRequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=200)),
                ('referer', models.CharField(blank=True, max_length=300, verbose_name='유입 경로')),
                ('visits', models.IntegerField(default=1, verbose_name='방문 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 방문 시간')),
            ],
            options={
                'verbose_name': 'Request 정보',
                'verbose_name_plural': 'Request 정보(들)',
            },
        ),
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '리다이렉트 경로',
                'verbose_name_plural': '리다이렉트 경로(들)',
            },
        ),
    ]
