# Generated by Django 2.1.2 on 2018-11-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httprequestinfo',
            name='visits',
        ),
    ]
