# Generated by Django 2.1.2 on 2019-01-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_httprequestinfo_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('entry_name', models.CharField(max_length=100, unique=True, verbose_name='유입 경로 이름')),
                ('redirect_url', models.URLField(verbose_name='이동시킬 경로')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀(들)',
            },
        ),
        migrations.AddField(
            model_name='httprequestinfo',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.TrackingGroup', verbose_name='팀'),
        ),
    ]
