# Generated by Django 2.1.2 on 2019-01-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_add_trafficgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redirection',
        ),
    ]
