# Generated by Django 2.1.2 on 2019-01-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_delete_redirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httprequestinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.TrackingGroup', verbose_name='팀'),
        ),
    ]
